[tool.poetry]
name = "betterconf"
version = "1.0.0"
description = "Python configs for humans."
authors = ["prostomarkeloff"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pre-commit = "^1.20.0"
mypy = "^0.761"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
